services:
  database:
    container_name: immobiliarisplus-db
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_DATABASE: immobiliarisplus
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  backend:
    container_name: immobiliarisplus-be
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/immobiliarisplus
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: secret

volumes:
  mysqldata: